### PR TITLE
Login and repos

### PR DESCRIPTION
**Pull request by korthout**
I fixed the tests for the list-repos feature. However, after merging in the new login functionality I was unable to get it working again. I could use some help to get it fixed.

### CODE REVIEW

**Comment by JohnGorter** [comment]
Ben je morgen op kc? Ik kan dan wel helpen.

**Comment by nicojs** [comment]
Yes I am. Please keep it English here :+1:

**Comment by korthout** [comment]
Sorry I won't be there. But if you see any possible solutions please inform me. I have time tomorrow evening to continue working on this ;)

**Comment by nicojs** [comment]
> However, after merging in the new login functionality I was unable to get it working again

@korthout what is the problem? It isn't working with the 'real' backend? Or with stubbed/mocked data?

**Comment by korthout** [comment]
I can't seem to get the frontend to work in a browser. That also means the angular tests, because these rely on the components to be rendered in a browser.

**Comment by nicojs** [comment]
Ok, i'll try to have a look later today

**Comment by nicojs** [comment]
I fixed some things. @korthout  can i give you a call later so i can explain what i did?

list-of-repos

**Comment by korthout** [comment]
I'm very interested in how you got it working, but sadly I just went home sick. So perhaps tomorrow. I'm great to hear you got it working though.

**Comment by nicojs** [comment]
Ok, give me a call when you've got the time ☎️ (~12.05h would be best)

**Pull request merged**
